### ISSUE TITLE
ExpandText.maxLength ?

### ISSUE THREAD

**Issue by taosimple** [jesusrp98/expand_widget#10]
ExpandText.maxLength should be maxLines

**Comment by jesusrp98** [comment]
You're right. Planning to update most of the features this package offers over the next few weeks.

Going to take your suggestion into consideration.

**Comment by jesusrp98** [comment]
Sorry it took so long but it's finally fixed! This feature is now available on the `dev` branch, but a new version will be available very soon!

This WILL be a breaking change, so keep that in mind.
