### ISSUE TITLE
[Feature list] v1.0

### ISSUE THREAD

**Issue by jesusrp98** [jesusrp98/expand_widget#13]
I'm going to lay down most of the new features & enhancements that will be implemented in the v1.0 update. All chages will reside inside the `dev` branch.
 - Fix #10 
- Implement #7 and resolve #8
- Add testing
- Add CI to the project
- More things comming soon...

Write a comment if you want your idea to be included in this new update!
Thanks for your collaboration :)

**Comment by jesusrp98** [comment]
New things have been added!
- Custom arrow icons!
- You can now render the arrow's alongside it (only arrow, only text or both!)
- Added default i18n to arrow hint labels
- Tweaked lots of things.

Expect more features in the coming days!

**Comment by jesusrp98** [comment]
And one last very cool feature: the ability to hide the expansion arrow!
With `hideArrowOnExpansion` you can now hide programatically the arrow when its child expands.

This will be the last feature implemented in this huge release!
What's now left is to write ALL test code necesary, in order to get a pretty good code coverage.
It will take me about a week or so, so stay tuned!

**Comment by Zazo032** [comment]
As 1.0 has been released, could you provide a migration guide for the `ShowChild` deprecation?

**Comment by jesusrp98** [comment]
Yeah, I'll launch a small version later today with the info about how to upgrade!!

But basically, a `ShowChild` widget is just a simple `ExpandWidget` but display only text, and hide the 'expand' text once it's expanded. Both features have been implemented inside `ExpandWidget`, so the other component is redundant and will not be supported in future releases.

**Comment by jesusrp98** [comment]
Added! Here's the explanation:

```
This widget is now considered as **deprecated**, you should not use it.

In order to get the same functionallity offered by this widget,
just use a regular `ExpandChild` widget, with the `expandArrowStyle`
property set to `ExpandArrowStyle.text`, and `hideArrowOnExpanded`
set to `true`.
```

**Comment by Zazo032** [comment]
Thanks @jesusrp98!
