### ISSUE TITLE
[BUG] Too much white space?

### ISSUE THREAD

**Issue by manhDat0301** [jesusrp98/expand_widget#22]
If i enter text such as : "asddasdd asdsadasda vxcvxcvxcv nmbvlkbm mlcmvcxnvxcmvn nmnmnmcnmsa vncmnvmcvnmcn mnvcmnvcmnvmc mcnvmnvmcnv dskqjdksdd" it will auto generate more white space than i entered.

**Comment by jesusrp98** [comment]
Hey, could you share some screenshots related to this?

**Comment by manhDat0301** [comment]
> Hey, could you share some screenshots related to this?

i dont have a screenshot here. You can try display the the text "asddasdd asdsadasda vxcvxcvxcv nmbvlkbm mlcmvcxnvxcmvn nmnmnmcnmsa vncmnvmcvnmcn mnvcmnvcmnvmc mcnvmnvmcnv dskqjdksdd askdmkalsmdadks askdmaslkdmsaldamsd asdnjkasndasjkdad".

**Comment by jesusrp98** [comment]
I'm sorry, I'd need some example about what you're talking about. I can't test this without a more specific test scenario.
