### ISSUE TITLE
Is there any way to set default expanded value...?

### ISSUE THREAD

**Issue by rohitk1011** [jesusrp98/expand_widget#31]
Please let me know is any way to set the default value to be true so I can see my children widgets automatically whenever the screen open.

**Comment by jesusrp98** [comment]
At this moment, it's not possible to make the exanded state as a default. Howeverm it shouldn't be too dificult to implement. You'd need to expose the internal `_isExpanded` variable.

At this moment, I don't really have the time to implement this, but feel free to create a PR for this feature :)

**Comment by jesusrp98** [comment]
This feature will be implemented in the next release :)
