### ISSUE TITLE
How to manage arrow position as text?

### ISSUE THREAD

**Issue by kseyko35** [jesusrp98/expand_widget#33]
I want to manage arrow position, but i didn't deal with it. Can u help for this? I try to do arrow position like sample image. But its position is always center.
![expandedtext](https://user-images.githubusercontent.com/22561071/151415548-348d1679-da25-4b70-b9bb-7f6c8a6ea9f0.JPG)

Thank you for help

**Comment by jesusrp98** [comment]
This is a great feature. I'll be adding this in the next release!

(Sorry for the wait here)
