### ISSUE TITLE
ExpandText overflowed

### ISSUE THREAD

**Issue by giantss** [jesusrp98/expand_widget#42]
![801715737584_ pic](https://github.com/jesusrp98/expand_widget/assets/13778798/162e8997-188e-4d95-8ee5-51ee96053960)

How to deal with text overflow when ExpandText is expanded?

**Comment by JamesMcIntosh** [comment]
You should be including this widget inside a scrollable widget, i.e.`SingleChildScrollView`

**Comment by giantss** [comment]
OK, thanks
