### ISSUE TITLE
Show tooltip message next to arrow

### ISSUE THREAD

**Issue by JamesMcIntosh** [jesusrp98/expand_widget#7]
Would be nice to always show the tool tip message as it's not obvious you need to long press to show it.

**Comment by ian-pinto-ketto** [comment]
Or better still, allow Show More/Show Less text to be always displayed instead of down/up arrows.

**Comment by jesusrp98** [comment]
Thank you very much for the support you've been giving to this project over the last months. I'm really sorry I haven't got the time necesary to implement new features to this awesome package!

But now I HAVE! I've already done my very own implementation of this feature. It works like this:
- You now have the `expandArrowStyle` enum parameter:
- If expandArrowStyle == ExpandArrowStyle.icon only the icon will be displayed.
- If expandArrowStyle == ExpandArrowStyle.text only the hint or text will be displayed, hindig the arrow.
- If expandArrowStyle == ExpandArrowStyle.both both widgets will be render at the same time!

Let me know what you think about this implementation.
Thank you very much @JamesMcIntosh ! If you have further suggestions, please let me know!

**Comment by JamesMcIntosh** [comment]
Hi @jesusrp98, always happy to help! It looks good, will have to use it to give some more feedback.

**Comment by jesusrp98** [comment]
Weah! You can see all features this new update brings in the #13 issue.

Also, if you want to test them inside your project, use this:
```
carousel_pro:
  git:
    url: https://github.com/jesusrp98/expand_widget.git
    ref: dev
```
Keep in mind that there are a copule breaking changes in the v1.0 update!

**Comment by jesusrp98** [comment]
Closing this issue because launch of v1.0 is imminent. Thanks for all the feedback @JamesMcIntosh !
